CREATE TABLE template (
    id SERIAL PRIMARY KEY,
    "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP,
    "createdBy" INTEGER NOT NULL DEFAULT 0,
    "updatedBy" INTEGER,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "isDeleted" BOOLEAN NOT NULL DEFAULT false,
    "name" VARCHAR(100),
    "description" VARCHAR(255) NULL,
    "channel" VARCHAR(10)  CHECK ("channel" IN ('whatsapp', 'SMS', 'viber')),
    "templateType" VARCHAR(20) CHECK ("templateType" IN ('simple', 'interactive', 'external')),
    "status" VARCHAR(20) CHECK ("status" IN ('draft','pending', 'approved','error','rejected')),
    "clientTemplateId" VARCHAR(50),
    "HSMUserId" VARCHAR(50),
    "HSMPassword" VARCHAR(50),
    "ISDCode" VARCHAR(10),
    "language" VARCHAR(10),
    "businessContactNumber" VARCHAR(20),
    "tenantId" INTEGER NOT NULL,
    "providerTemplateId" VARCHAR(20)
);

CREATE TABLE "templateContentButtons" (
    id SERIAL PRIMARY KEY,
    "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP,
    "createdBy" INTEGER NOT NULL DEFAULT 0,
    "updatedBy" INTEGER,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "isDeleted" BOOLEAN NOT NULL DEFAULT false,
    "buttonType" VARCHAR(20) CHECK ("buttonType" IN ('quickReply', 'websiteVisit', 'flow')),
    "title" VARCHAR(100),
    "websiteUrl" VARCHAR(2000) NULL,
    "isDynamicUrl" BOOLEAN DEFAULT false,
    "isTrackUrl" BOOLEAN DEFAULT false,
    "navigateScreen" VARCHAR(255) NULL,
    "initialScreen" VARCHAR(255) NULL,
    "buttonId" VARCHAR(50) NULL,
    "buttonDescription" VARCHAR(255) NULL,
    "sectionId" INTEGER NULL,
    "flowId" VARCHAR(20) NULL,
    "flowAction" VARCHAR(20) NULL CHECK ("flowAction" IN ('navigate', 'data_exchange')),
    "flowToken" VARCHAR(20) NULL,
    "additionalData" JSONB NULL
);
CREATE TABLE "templateContentButtonsSection" (
    id SERIAL PRIMARY KEY,
    "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP,
    "createdBy" INTEGER NOT NULL DEFAULT 0,
    "updatedBy" INTEGER,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "isDeleted" BOOLEAN NOT NULL DEFAULT false,
    "name" VARCHAR(100) 
);

CREATE TABLE "templateContent" (
    id SERIAL PRIMARY KEY,
    "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP,
    "createdBy" INTEGER NOT NULL DEFAULT 0,
    "updatedBy" INTEGER,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "isDeleted" BOOLEAN NOT NULL DEFAULT false,
    "contentType" VARCHAR(8) NULL CHECK ("contentType" IN ('common', 'carousel')),
    "headerType" VARCHAR(5) NULL CHECK ("headerType" IN ('text', 'media')),
    "headerContent" VARCHAR NULL,
    "headerPlaceHolder" INTEGER[] DEFAULT '{}',
    "headerMediaType" VARCHAR(8) NULL CHECK ("headerMediaType" IN ('image', 'video', 'document', 'location')),
    "headerMediaUrl" TEXT NULL,
    "body" VARCHAR(1032) NULL,
    "bodyPlaceHolder" INTEGER[] DEFAULT '{}',
    "footer" VARCHAR(60) NULL,
    "contentUrl" TEXT NULL,
    "caption" VARCHAR(200) NULL,
    "latitude" DECIMAL(9, 6) NULL,
    "longitude" DECIMAL(9, 6) NULL,
    "locationName" VARCHAR(255) NULL,
    "address" VARCHAR(255) NULL,
    "isPreviewUrl" BOOLEAN DEFAULT false,
    "messageType" VARCHAR(8) NULL CHECK ("messageType" IN ('text', 'image', 'video', 'audio', 'file', 'location', 'sticker')),
    "messageText" VARCHAR(255) NULL,
    "buttonIds" INTEGER[] DEFAULT '{}',
    "contentSubType" VARCHAR(16) NULL CHECK ("contentSubType" IN ('common', 'requestLocation', 'address', 'flow')),
    "templateId" INTEGER NOT NULL,
    "actionType" VARCHAR(20) CHECK ("actionType" IN ('quickReply', 'menu')),
    "menuButtonName" VARCHAR(100),
    CONSTRAINT fk_templateId FOREIGN KEY ("templateId") REFERENCES template (id) ON DELETE CASCADE
);

CREATE TABLE "templateContentCards" (
    id SERIAL PRIMARY KEY,
    "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP,
    "createdBy" INTEGER NOT NULL DEFAULT 0,
    "updatedBy" INTEGER,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "isDeleted" BOOLEAN NOT NULL DEFAULT false,
    "mediaType" VARCHAR(5) CHECK ("mediaType" IN ('image', 'video')),
    "contentUrl" TEXT NULL,
    "body" VARCHAR(160) NULL,
    "bodyPlaceHolder" INTEGER[] DEFAULT '{}',
    "buttonIds" INTEGER[] DEFAULT '{}',
    "templateContentId" INTEGER NOT NULL,
    CONSTRAINT fk_templateContentId FOREIGN KEY ("templateContentId") REFERENCES "templateContent" (id) ON DELETE CASCADE
);