CREATE TABLE template (
    id SERIAL PRIMARY KEY,
    "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP,
    "createdBy" INTEGER NOT NULL DEFAULT 0,
    "updatedBy" INTEGER,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "isDeleted" BOOLEAN NOT NULL DEFAULT false,
    "name" VARCHAR(100),
    "description" VARCHAR(255),
    "channel" VARCHAR(10) CHECK ("channel" IN ('whatsapp', 'SMS', 'viber')),
    "templateType" VARCHAR(12) CHECK ("templateType" IN ('simple', 'interactive', 'external')),
    "status" VARCHAR(12) CHECK ("status" IN ('draft','pending', 'approved')),
    "clientTemplateId" VARCHAR(50),
    "HSMUserId" VARCHAR(50),
    "HSMPassword" VARCHAR(50),
    "ISDCode" VARCHAR(10),
    "language" VARCHAR(10),
    "businessContactNumber" VARCHAR(20),
    "tenantId" INTEGER NOT NULL
);

CREATE TABLE "templateContentButtons" (
    id SERIAL PRIMARY KEY,
    "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP,
    "createdBy" INTEGER NOT NULL DEFAULT 0,
    "updatedBy" INTEGER,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "isDeleted" BOOLEAN NOT NULL DEFAULT false,
    "buttonType" VARCHAR(12) CHECK ("buttonType" IN ('quickReply', 'visitWebsite', 'menu')),
    "actionType" VARCHAR(12) CHECK ("actionType" IN ('quickReply', 'menu')),
    "title" VARCHAR(25),
    "websiteUrl" VARCHAR(2000),
    "isDynamicUrl" BOOLEAN,
    "navigateScreen" VARCHAR(255),
    "initialScreen" VARCHAR(255),
    "flowId" VARCHAR(20),
    "flowAction" VARCHAR(12) CHECK ("flowAction" IN ('navigate', 'dataExchange')),
    "flowToken" VARCHAR(20)
);

CREATE TABLE "templateContent" (
    id SERIAL PRIMARY KEY,
    "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP,
    "createdBy" INTEGER NOT NULL DEFAULT 0,
    "updatedBy" INTEGER,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "isDeleted" BOOLEAN NOT NULL DEFAULT false,
    "contentType" VARCHAR(8) CHECK ("contentType" IN ('common', 'carousel')),
    "headerType" VARCHAR(5) CHECK ("headerType" IN ('text', 'media')),
    "headerContent" VARCHAR,
    "headerPlaceHolder" INTEGER[] DEFAULT '{}',
    "headerMediaType" VARCHAR(8) CHECK ("headerMediaType" IN ('image', 'video', 'document', 'location')),
    "body" VARCHAR(1032),
    "bodyPlaceHolder" INTEGER[] DEFAULT '{}',
    "footer" VARCHAR(60),
    "contentUrl" TEXT,
    "caption" VARCHAR(200),
    "latitude" DECIMAL(9, 6),
    "longitude" DECIMAL(9, 6),
    "address" VARCHAR(255),
    "isPreviewUrl" BOOLEAN,
    "isTrackUrl" BOOLEAN,
    "messageType" VARCHAR(8) CHECK ("messageType" IN ('text', 'image', 'video', 'audio', 'file', 'location', 'sticker')),
    "buttonIds" INTEGER[],
    "contentSubType" VARCHAR(16) CHECK ("contentSubType" IN ('common', 'requestLocation', 'address', 'flow')),
    "additionalData" TEXT,
    "templateId" INTEGER,
    CONSTRAINT fk_templateId FOREIGN KEY ("templateId") REFERENCES template (id) ON DELETE CASCADE
);

CREATE TABLE "templateContentCards" (
    id SERIAL PRIMARY KEY,
    "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP,
    "createdBy" INTEGER NOT NULL DEFAULT 0,
    "updatedBy" INTEGER,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "isDeleted" BOOLEAN NOT NULL DEFAULT false,
    "mediaType" VARCHAR(5) CHECK ("mediaType" IN ('image', 'video')),
    "contentUrl" TEXT,
    "body" VARCHAR(160),
    "bodyPlaceHolder" INTEGER[] DEFAULT '{}',
    "buttonIds" INTEGER[],
    "templateContentId" INTEGER,
    CONSTRAINT fk_templateContentId FOREIGN KEY ("templateContentId") REFERENCES "templateContent" (id) ON DELETE CASCADE
);